### ISSUE TITLE
<corecrt.h> redefinition warnings and assert.h(17,1) syntax error

### ISSUE THREAD

**Issue by golxzn** [wxWidgets/wxWidgets#24851]
### Environment

```toml
[System]
  name    = "Windows 11 Pro"
  version = "23H2"
  build   = "22631.4169"

[Compiler]
  MSVC           = "17 2022"
  version        = "19.40.33813"
  toolset        = "v143"
  system_version = "10.0.22631"

[Build System]
  CMake        = "3.30.3"
  CXX_FLAGS    = "/MP12 /EHsc /Oi"
  cpp_standard = 17
  c_standard   = 11
  architecture = "x64"

[wxWidgets]
  version = "3.3.0"
  port    = "wxMSW"
```

### Description

I'm trying to build and link the `wxWidgets` library as the subdirectory:

```CMake
set(wxBUILD_COMPATIBILITY 3.2)
set(wxBUILD_PRECOMP       OFF)
set(wxBUILD_SHARED        OFF)
set(wxBUILD_MONOLITHIC    OFF)

add_subdirectory(${CD_DEPS_DIR}/wxWidgets "editor_deps/wxWidgets" EXCLUDE_FROM_ALL)
target_link_libraries(${target} PRIVATE wx::core wx::base wx::gl)
```

And I get the following warnings twice:

```build
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\commctrl.h(205,9): warning C4005: 'CCM_SETUNICODEFORMAT': macro redefinition [G:\proj\build\msvc_editor\code\editor\editor_deps\wxWidgets\libs\core\wxcore.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\commctrl.h(714,9): warning C4005: 'HDS_HOTTRACK': macro redefinition [G:\proj\build\msvc_editor\code\editor\editor_deps\wxWidgets\libs\core\wxcore.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\commctrl.h(2982,9): warning C4005: 'CCS_RIGHT': macro redefinition [G:\proj\build\msvc_editor\code\editor\editor_deps\wxWidgets\libs\core\wxcore.vcxproj]
```

And those errors:

```log
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\assert.h(17,1): error C2059: syntax error: 'extern ' [G:\proj\build\msvc_editor\cd2.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\assert.h(17,1): error C2143: syntax error: missing ';' before '{' [G:\proj\build\msvc_editor\cd2.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\assert.h(17,1): error C2447: '{': missing function header (old-style formal list?) [G:\proj\build\msvc_editor\cd2.vcxproj]
```

---

Seems like the `"wx/msw/missing.h"` file somehow includes just before the `<commctrl.h>`, but I cannot get how would it be.
